package com.dah.nrs

import com.dah.nrs.dsl.*
import com.dah.nrs.exts.*

fun DSLScope.Arifureta() {
    Entry {
        id = "F-VGMDB-6083"
        title = "Arifureta Shokugyou de Sekaisaikyou"

        Entry {
            id = "A-MAL-36882"    // generated
            idMAL = 36882
            idAniList = 100668
            idAniDB = 13624
            idKitsu = 14043
            title = "Arifureta Shokugyou de Sekai Saikyou"
            bestGirl = "Yue"

            Progress(Boredom.Completed)

            // MC got dumped by his friends made me kinda angry
            NEI(2.5, Emotion.AU)
            Visual(VisualKind.Animated, 0.5, 0.1)

            FeatureMusic("M-VGMDB-AL-86592-1")
        }

        Contains("M-VGMDB-AL-86592-1")
    }

    Entry {
        id = "M-VGMDB-AL-86592"
        title = "FLARE / Void_Chords feat.LIO" // generated by fill_metadata.dart v0.1.1

        Visual(VisualKind.AlbumArt, 0.05, 0.5)
        SubIDEntry("1") {
            title = "FLARE" // generated by fill_metadata.dart v0.1.1
            Music(1.0)
            OsuSong(personal = 1.0, community = 0.5)
        }
    }
}
