package com.dah.nrs

import com.dah.nrs.dsl.*
import com.dah.nrs.exts.*

fun DSLScope.BunnyGirlSenpai() {
    Entry {
        id = "F-VGMDB-6852"
        title = "Seishun Buta Yarou Series"

        Entry {
            id = "A-MAL-37450"
            title = "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai"
            bestGirl = "Makinohara Shouko"

            Progress(Boredom.Dropped)
            ValidatorSuppress("dah-uncompleted-no-progress")
            // plot kinda ok
            NEI(5.0, Emotion.AP)
            Visual(VisualKind.Animated, 0.6, 0.15)
            FeatureMusic("M-VGMDB-AL-80253-1")
        }

        Contains("M-VGMDB-AL-80253-1")
    }

    Entry {
        id = "M-VGMDB-AL-80253"
        title = "Kimi no Sei / the peggies" // generated by fill_metadata.dart v0.1.1

        // tf is this lol
        Visual(VisualKind.AlbumArt, 0.1, 0.6)

        SubIDEntry("1") {
            title = "Kimi no Sei" // generated by fill_metadata.dart v0.1.1
            Music(1.0)
        }
    }
}
