package com.dah.nrs.meme

import com.dah.nrs.AKMEraPart1
import com.dah.nrs.dsl.*
import com.dah.nrs.exts.*

// modern vietnamese literature
fun DSLScope.MVLiterature() {
    // based rst turning literally everything into a meme
    // (those texts getting their own entries is a way to nerf rst/sb69 btw)
    Entry {
        id = "O-2"
        title = "Người lái đò Sông Đà"

        // the river analogy states that the love live franchise is our opponents/enemies
        // (Sông Đà hung bạo) as well as our friends (Sông Đà trữ tình)
        AKMEraPart1(0.15)
    }

    Entry {
        id = "O-3"
        title = "Vợ chồng A Phủ"

        // there are several analogies for this
        // first, the MC of the story can be thought of a representation of the gigachad mapper,
        // who isn't that active with rst anymore. The "Mi" analogy states that deep down
        // in their heart, the gigachad mapper still loves rst like in "the glory days".

        // second, some 4chan mfs said that Akari Kito ditched rst.
        // The analogy states that this situation is because of her
        // being forced to do that.

        // both analogies value the "intense latent vitality" of rst mfs

        // also the character "A Sử" made the famous meme
        // "A-Sử-iro Koi Moyou"
        AKMEraPart1(0.25)
    }

    Entry {
        id = "O-4"
        title = "Chiếc thuyền ngoài xa"
        // https://vi.wikipedia.org/wiki/Chi%E1%BA%BFc_thuy%E1%BB%81n_ngo%C3%A0i_xa

        // the "faraway boat" analogy
        // basically states that popular shit may have good songs, fanarts, etc.
        // but deep down, they are evil (in my shitty culture)
        // this not only acts as my admittance to these franchises that their shit are
        // high quality, but also as an excuse for me to never touch their stuff.

        // Spy x Family was the anime that makes this a meme.
        // And then "Asuiro Clear Sky" (i found this while searching for Asuiro Koi Moyou)
        // became the "theme song" of this.
        // FYI: Asuiro Clear Sky is a song from Hololive IDOL PROJECT

        // le boat analogy is canon poggers
        // A certified "Mũi thuyền in một nét mơ hồ lòe nhòe vào bầu sương mù trắng như
        // sữa có pha đôi chút màu hồng hồng do ánh mặt trời chiếu vào" moment

        // 今日、2021年7月7日、ベトナムでは卒業試験です。昨日、この人、キッドのような名前は
        // 「国語はChiếc thuyền ngoài xaと思います」ってフェスブックで言ったことがあります。
        // 2年前、この人も2回正しい卒業試験の国語の答えを行った、
        AKMEraPart1(0.3)
    }

    Entry {
        id = "M-VGMDB-AL-111027"
        title = "hololive IDOL PROJECT / Bouquet" // generated by fill_metadata.dart v0.1.0

        Visual(VisualKind.AlbumArt, 0.5, 0.3)

        SubIDEntry("10", "Asuiro ClearSky") {
            title = "あすいろClearSky (Bouquet Ver.)" // generated by fill_metadata.dart v0.1.0
            // asuiro koi moyou and its consequences
            // hololiveshit stole rst & sb69 composer
            // hololiveshit stole rst & sb69 composer
            // hololiveshit stole rst & sb69 composer
            // hololiveshit stole rst & sb69 composer
            // hololiveshit stole rst & sb69 composer
            // hololiveshit stole rst & sb69 composer
            // hololiveshit stole rst & sb69 composer
            // hololiveshit stole rst & sb69 composer

            // >【Works】Re:ステージ!/ホロライブ(全体曲,1期生,3期生)/SHOW BY ROCK!!/La prière/...
            // how dare hololiveshit sit between two glorious franchises (or three idk)
            // these mfs need to touch grass and realize how shitty they are
            // compared to rst and sb69, "the franchises of all time"
            Music(6.5)
            // the girls look CG af, but at least the other things are good
            Visual(VisualKind.SemiAnimatedMV, 0.3, 0.2)
            AKMEraPart1(0.4)
            AKMEraPart1(0.1)
        }
    }
}
