name: Update without sync

on: [push, workflow_dispatch]

jobs:
  update-without-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
    - name: Install Dart dependencies
      run: dart pub get
      working-directory: ./nrs_mod
    - name: Create (dummy) user-secrets.py
      run: "echo 'AOD_PATH=\"anime-offline-database/anime-offline-database-minified.json\"' > scripts/sync/services/user_secrets.py"
    - name: (Debug) cat user-secrets.py
      run: cat scripts/sync/services/user_secrets.py
    - name: Install npm dependencies for make_csv.js
      run: npm install
      working-directory: ./scripts
    - name: Run Gradle task :updateWithoutSync
      run: ./gradlew updateWithoutSync
    - name: Make commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore(impl): :package: Update without sync'
    - name: Upload generated files as a release
      uses: marvinpinto/action-automatic-releases@latest
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-${{ github.ref_name }}"
        title: "Release #${{ github.run_number }}"
        prerelease: false
        files: |
          output/entries.json
          output/scores.json
          output/impacts.json
          output/relations.json
          output/nrs.csv
